# Generated by Django 5.0.4 on 2024-04-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasascambiobcv',
            name='precio_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
