# Generated by Django 5.0.4 on 2024-04-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCV', '0002_alter_tasascambiobcv_precio_anterior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasascambiobcv',
            options={'verbose_name_plural': 'Tasas de Cambio BCV'},
        ),
    ]
