# Generated by Django 5.0.4 on 2024-04-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasasCambioExMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultima_actualizacion', models.DateField()),
                ('percent', models.CharField(max_length=10)),
                ('change', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
    ]
