# Generated by Django 5.0.4 on 2024-04-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeMonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasascambioexmon',
            options={'verbose_name_plural': 'Tasas de Cambio Exchange Monitor'},
        ),
    ]
